name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

  # Allows manual execution from the GitHub Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://arnab9957:$HF_TOKEN@huggingface.co/spaces/arnab9957/redrob-ranker
          git push --force hf main
